plugins {
    id 'application'
    id 'org.openjfx.javafxplugin' version '0.0.13'
}

java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}

dependencies {
    implementation project(':common')

    implementation 'org.apache.logging.log4j:log4j-api:2.23.1'
    implementation 'org.apache.logging.log4j:log4j-core:2.23.1'
}

javafx {
    version = '17.0.10'
    modules = ['javafx.controls', 'javafx.fxml']
}

application {
    mainClass = 'ro.mpp2026.StartApplication'
}