jakarta.persistence.jdbc.driver=org.sqlite.JDBC
jakarta.persistence.jdbc.url=jdbc:sqlite:server/contest.db

hibernate.dialect=org.hibernate.community.dialect.SQLiteDialect
jakarta.persistence.schema-generation.database.action=update

hibernate.show_sql=true
hibernate.format_sql=true
hibernate.highlight_sql=true
hibernate.use_sql_comments=true
hibernate.generate_statistics=true